Repository maximiseuk/onlinestudytools, pull requests merged in 2020-01, with the labels that each got.

#27 Tools
  .gitignore
  README.md
  package-lock.json
  package.json
  public/agenda.json
  public/get_data.json
  public/goals.json
  public/images/book.png
  public/images/box.png
  public/images/dots2.png
  public/images/error.jpeg
  public/images/flower.png
  public/images/keyboard.png
  public/images/logo.png
  public/index.html
  public/timetable.json
  src/api/advice.json
  src/api/faqs.json
  src/api/function.js
  src/components/Advice.js
  src/components/Agenda.js
  src/components/App.js
  src/components/Goals.js
  src/components/Help.js
  src/components/Home.js
  src/components/LandingPage.js
  src/components/Login.js
  src/components/Navigation.js
  src/components/Page404.js
  src/components/PageLoadError.js
  src/components/Settings.js
  src/components/Signup.js
  src/components/SnackbarError.js
  src/components/Timetable.js
  src/components/TopBar.js
  src/index.css
  src/index.js
  src/ml/index.js
  src/reducers/index.js
  src/reducers/subjects.js
  src/reducers/theme.js
Labels: enhancement

#28 Landing page
  package-lock.json
  src/components/App.js
  src/components/LandingPage.js
  src/components/Signup.js
  src/components/Timetable.js
  src/index.css
Labels: enhancement

#34 Add ML
  server_ready_code.ipynb
Labels: programming

#33 fixed random "#"
  README.md
Labels: documentation
